### ISSUE TITLE
Object containing array with doctrine entities

### ISSUE THREAD

**Issue by nusje2000** [aeviiq/storage-manager#7]
When you create an object containing a property with an array of doctrine entities, this cannot be stored via the storage manager. Example:
```php
class SomeModel
{
    /**
     * @var DoctrineEntity[]
     */
    private $entities;
}
```
I use the following code:
```php
$someModel = new SomeModel();
$someModel->setEntities([
    new DoctrineEntity('identifier 1'),
    new DoctrineEntity('identifier 2'),
]);

$storageManager->save($someModel);
```
I would expect the following object to be saved:
```
SomeModel
 | - entities
   | - StorableEntity(['id' => 'identifier 1'])
   \ - StorableEntity(['id' => 'identifier 2']) 
```
But the items in the array are not mapped to StorableEntitie's and thus throwing an exception because of references the entities might have to classes like a ReflectionClass (due to doctrine's behavior) which cannot be cloned by `myclabs/deep-copy`.

**Comment by aeviiq** [comment]
Added this feature in https://github.com/aeviiq/storage-manager/pull/8
